### PR TITLE
update module jwks_rsa

### PR DESCRIPTION
**Pull request by AntoineGUENEAU**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](/okta/okta-oidc-js/blob/master/CONTRIBUTING.md#commit)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Adding Tests
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

Merge request linked to issue #21 

The purpose is updating the librairie : "jwks-rsa"

### CODE REVIEW

**Review by joshuachoi0508 — APPROVED** [review]

**Review by joshuachoi0508 — APPROVED** [review]

**Comment by AntoineGUENEAU** [comment]
Thanks for this approval @joshuachoi0508  :)
Can you merge and create a new release ?

**Comment by rajat-sg** [comment]
@oleksandrpravosudko-okta
can you please merge this?

**Review by Tantawi — APPROVED** [review]

**Comment by Tantawi** [comment]
@arunelengovan-okta  @bjr-okta @releng-internal-okta @drewhall-okta

Can we please merge this asap?

**Comment by aliwatters** [comment]
https://github.com/okta/okta-jwt-verifier-js/issues/21
https://github.com/jwtk/njwt

at Okta -- please fork and fix and use `https://github.com/okta/njwt` -- or depend on a maintained library.

Thank you!

**Comment by AntoineGUENEAU** [comment]
@aliwatters @Tantawi Do you have some news ?

**Comment by rcollette** [comment]
I just opened a support case myself.  It is surprising that Okta is awol on this.

**Comment by jaredperreault-okta** [comment]
thanks all for your patience, we have released an update (3.0.0) which upgrades these packages

**Pull request closed without merging**
